### PR TITLE
Integrating MRA and VSA Results with IR

### PR DESCRIPTION
**Pull request by yousifpatti**
- Replaces stack memory stores/loads with "stack" instead of "mem"
- Replaces memLoads with concrete values

### CODE REVIEW

**Comment by ailrst** [comment]
This looks good except for the OR between multiple VSA possibilities, I don't think we can use Exprs to represent nondeterministic choice this way

**Comment by l-kent** [comment]
Yeah, you can't represent non-deterministic choice that way. If an access could be to multiple regions, then you need to merge those regions together in the IR.

**Comment by l-kent** [comment]
To do non-deterministic choice you need to add a block for each choice, and a GoTo that points to both blocks (`goto Block1, Block2;` in Boogie. This is not currently supported in the IR but would be easy to implement - see #64. You would also need to add Assumes (also not in the IR yet but easy to implement) to the start of each of the choices to represent the branching conditions, which would be that the acces index equals each of the possible values corresponding to different regions.

This is probably worth experimenting with in comparison to merging the regions, but I'm not sure how effective it would be. It might prove difficult with say, heap accesses where you don't have a static value; I'm not sure.

We will likely need non-deterministic choice to some extent regardless, in order to maintain stack regions separate from other memory regions.

**Comment by l-kent** [comment]
We also don't want to be replacing the `MemoryLoad`s with concrete values like that, as discussed yesterday. Our aim is to replace the `mem` variable in `MemoryLoad`s and `MemoryStore`s with a new `Memory` variable that represents the region being accessed in each case.

**Pull request merged**
