### PR TITLE
Basil 12 - Thread Identification

### PR DESCRIPTION
**Pull request by ziggyfish**

### CODE REVIEW

**Comment by l-kent** [comment]
We can't really merge this into main until the analysis branch is merged into main properly, since this is a fork of one of those branches.

**Comment by ailrst** [comment]
> We can't really merge this into main until the analysis branch is merged into main properly, since this is a fork of one of those branches.

We'll merge into analysis devel first

**Comment by ailrst** [comment]
I'd prefer to use value set analysis result rather than the constant propagation analysis result; this means we make a more conservative estimate of the possibly-concurrent procedures (we get all the possible values in constant-prop plus more). Plus this matches how we resolve regular indirect calls.

**Comment by ziggyfish** [comment]
@ailrst I agree we should use VSA, however register R2 doesn't exist in the VSA but does exist in the constant propegation analysis. So work needs to be done, before we can use constant VSA.

**Comment by ailrst** [comment]
> @ailrst I agree we should use VSA, however register R2 doesn't exist in the VSA but does exist in the constant propegation analysis. So work needs to be done, before we can use constant VSA.

That means the VSA is most likely not working correctly, I'll have to look into it

**Comment by l-kent** [comment]
What is the status of this? Is it working except we want to use VSA instead of constant propagation but there is an issue preventing that? If someone explains the problem with the VSA in further depth and creates an issue for it, I can try to fix that.

**Comment by ailrst** [comment]
VSA should be fixed now in analysis-devel and the main branch

**Comment by ziggyfish** [comment]
Looks like there are a few issues still with the VSA, so I can't do anything with this yet, and how its structured.

So seems that this code also has many conflicts other changes in the code.

So I'll leave it with you guys to make the nessecary changes to get this into a state where it can be merged with main.

Some documentation:

The most of the work is done in analysis.DirectCallAnalysis and analysis.call.ThreadAnalysis.

Essentially it simply looks at the value of R2 and uses this as the entry point into the thread analysis.

Anyway I'll leave it with the rest of the team to handle the required changes.

**Comment by l-kent** [comment]
Can you explain what the issues are with the VSA? In main, R2 is definitely in the VSA result for the pthread example at the pthread_create callsite, so it isn't the issue you were previously talking about.

**Comment by l-kent** [comment]
This is not the approach that will make sense for dealing with threads

**Pull request closed without merging**
